### ISSUE TITLE
sometims muted

### ISSUE THREAD

**Issue by ewonais** [cpiber/NebulaEnhance#1]
sometimes videos starts muted
i am unable to find a pattern
it dident happen before i started using the extension

**Comment by cpiber** [comment]
I will look into that!
What browser and OS are you using? Could you please send me a screenshot of your settings?

**Comment by ewonais** [comment]
cromium (vivaldi)
windows 10
![image](https://user-images.githubusercontent.com/86527854/123518968-c00f2580-d6a8-11eb-9ee7-5b06ee779e03.png)
![image](https://user-images.githubusercontent.com/86527854/123519024-25631680-d6a9-11eb-98ee-c5ee20556713.png)
![image](https://user-images.githubusercontent.com/86527854/123519160-e5506380-d6a9-11eb-8c50-06b30a6cb425.png)

**Comment by cpiber** [comment]
Sorry, I only got to this now.
After a bit of digging, it seems this happens because modern browsers do not allow autoplay with audio: http://demo.theoplayer.com/autoplay-policy
Sadly I can't do anything against this, so if you don't like it, please disable autoplay.

In Firefox you can allow autoplay with audio per site (like other permissions), in Chromium it seems to be allowed all the time (on my install at least). For Vivaldi, you'll have to search for yourself. chrome://flags/#autoplay-policy  might be a good tip.
