### ISSUE TITLE
Channel name as a link to the channel, not to the video

### ISSUE THREAD

**Issue by dereineLauch** [cpiber/NebulaEnhance#20]
Currently, when you click on the channel name next to a video, you still get to the video (see picture) - that doesn't make sense to me. You Only get to the channel when you click on the profile picture. 
![image](https://user-images.githubusercontent.com/84781281/159175221-901f5dfa-ab38-4b43-a351-1633ba027d1f.png)
So I want it to also take me to the channel when I click on the channel name.

**Comment by cpiber** [comment]
You can click on the icon ;)

**Comment by cpiber** [comment]
I also don't plan on changing that, because currently the only indicator on whether the video was already seen is via that line, so if I were to change that link, the indicator wouldn't work anymore. And it does not seem possible to make any other part react to it, due to the constraints on the `:visited` selector.
