### ISSUE TITLE
hide watched videos

### ISSUE THREAD

**Issue by ewonais** [cpiber/NebulaEnhance#26]
i wold like to be able to hide watched videos from my subscription feed
for youtube i use "Better Subscriptions for YouTube™"

**Comment by cpiber** [comment]
So, on https://nebula.app/videos you want the watched videos to disappear, like for hidden creators?

Since nebula now stores watch time, I think it should be possible. Keep in mind that this can fail (I see several videos where no watch progress has been recorded for my account). I'd also hide videos that have *any* watch progress, not just completely watched.

**Comment by dereineLauch** [comment]
> I'd also hide videos that have any watch progress, not just completely watched.

Why? I think only fully watched videos should be hidden.

**Comment by cpiber** [comment]
> Why? I think only fully watched videos should be hidden.

It depends on your preference I guess. I'm not really using such a feature, but I can see why you would want to hide partially watched videos, f.e. if you stopped watching it because it wasn't interesting anymore.

The other is ease of implementation :sweat_smile: It's easy to detect that a bar is there (because Nebula just doesn't create it if you haven't watched), but checking the progress won't be. I have to see if I can extract it from the DOM somehow, I really don't want to make a request per video, that would probably result in bans...
