### ISSUE TITLE
Queue button covers Add to Watch Later button

### ISSUE THREAD

**Issue by n2burns** [cpiber/NebulaEnhance#29]
Could we have an option in the settings to fully disable the queue? Now that Nebula has a built in Watch Later, I personally prefer to use that. The main issue is queue button replaces the "Add to Watch Later" in the top right of the video's thumbnail.

**Comment by cpiber** [comment]
It should not replace anything. This extensions "add to queue" button is strictly below nebula's "add to watch later". If it does, please send me your browser details (and check you are on the latest version of the extension).

Personally I don't see much sense in adding that option, since the only change is that button anyways, so if it's working correctly it should not be a problem.

**Comment by n2burns** [comment]
Oh, that's not how it appears for me
![Nebula enhancer](https://user-images.githubusercontent.com/431090/184235815-cd7993c0-f3ec-4cf7-af02-03f93aec030a.png)
Google Chrome v103.0.5060.132
Enhancer for Nebula 1.1.3

I experience the same thing on my

**Comment by cpiber** [comment]
Thank you, in that case that's a bug in the chrome version, in Firefox it works correctly. Unfortunately my Linux PC is a touch device, so chrome does not show me the desktop version, I'll have to see if I can find a different device to debug this, so it might be a while until I can fix this

**Comment by n2burns** [comment]
I was able to try it on my Linux laptop, and I was wrong, it appears correctly there, both in Firefox and Chrome.

The device with the issue is a Chromebook. Please let me know if there any troubleshooting/debugging I can do.

Thanks for your time and help!

**Comment by cpiber** [comment]
Thank you for investigating! I don't have one, so that will be difficult... Are you familiar with DevTools/Inspector? If so, could you please send a screenshot of the styles of the button (see screenshot)? For that, please right-click the "Add to watch later" button, then find the parent div with "enhancer-queueButton" class.

![image](https://user-images.githubusercontent.com/59023762/184354480-b07324c0-5d23-46d9-aa1e-46f041ec0195.png)

**Comment by cpiber** [comment]
I just checked, is it possible the Chromebook is a touch device? If so, can you see Nebula's "Add to Watch Later" button without the extension? If not, I think this is the situation:

The button only appears on hover, but it's impossible to hover on a touch device and Nebula doesn't handle this specially, so it's just always hidden (though it can still be clicked if you know it's there). Enhancer on the other hand detects the touch device and forces the "Add to queue" button to always be visible. To not leave a gap, I move it up.

However, it appears since recently the "Add to Watch Later" button is actually there all the time, just not visible, so it might be possible to force it to appear from my extension, I'll investigate that.

**Comment by cpiber** [comment]
Could you please try installing this version and see if that fixes it @n2burns ?
[enhancer_for_nebula-1.1.3.zip](https://github.com/cpiber/NebulaEnhance/files/9349434/enhancer_for_nebula-1.1.3.zip)

**Comment by n2burns** [comment]
Sorry, I didn't get around to using the DevTools. Yes, the Chromebook is a touch device, and the updated version you provided works perfectly!

**Comment by cpiber** [comment]
Great :) Then I'll put that in the next version
