### ISSUE TITLE
Hide watched videos by filtering the web request

### ISSUE THREAD

**Issue by ModProg** [cpiber/NebulaEnhance#33]
Not 100% sure how this could be done, but should be possible (at least on firefox, not sure what v3 would change on chrome).

I'd propose to take the request to query more videos and filter the returned json i.e. removing the already watched ones.

This would improve performance I think as the website wouldn't need to load the thumbnails, and also less jumpy with them shortly appearing and then getting removed.

**Comment by cpiber** [comment]
I did consider that, not sure how feasible it is. I already somewhat modify XMLHttpRequest (which Nebula uses), so it might not be that far off. I did not want to do that, since that is getting dangerously close to a sniffer (I'll have to check all requests)...

Not sure if v3 changes anything for me, at least at the moment I think I can still upload v2 extensions, just not make new ones. I hope having to convert will still be a bit off...

**Comment by ModProg** [comment]
Well personally I don't think there is a big difference to modify all requests pointing to `https://content.api.nebula.app/library/video/` or modifying the dom.

**Comment by cpiber** [comment]
Took me a bit of tinkering, but I managed to do it. It really *is* nice to see the videos not even appear. The old DOM-based code is still there as fallback, as that is less tied to the API and should thus be more stable/just work.

**Comment by ModProg** [comment]
Just tried this out. works perfectly!

**Comment by cpiber** [comment]
Great! I'll publish the new version some time in the next days, I want to see if there might be some progress on #34 first.

**Comment by ModProg** [comment]
I was thinking about the future possibilities of filtering the API response, e.g. allow filtering by video length/release date etc.

My idea was to add a button to the video list where you can open a filter settings drop-down and set the options to filter by, with a `Apply & Reload` button to trigger refetching and filtering of results.

I wanted to look into this, but I was a bit overwhelmed by the size of the codebase, having no experience with extension development. Maybe I'll look into it some time in the future when I find the time to actually dive into the inner workings a bit.

**Comment by cpiber** [comment]
It sounds like an interesting idea... First you'd need to think about how you actually let the user specify the field, comparison and value. The options page is `src/options.html`, form code is usually in `src/scripts/options/form.ts`.

When you have that, you can implement it. This specific feature currently lives in `src/scripts/page/xhrfilters.ts`. At that point you'd probably need to refactor a bit, since I currently have more or less copy-pasted for the two requests I need to handle, but with your more complex implementation that's not acceptable anymore.
