### ISSUE TITLE
[Feature Request] Fullscreen/Maximize Video Mode

### ISSUE THREAD

**Issue by BubiBalboa** [cpiber/NebulaEnhance#48]
I would love to have a more extreme version of theater mode where the video is using the whole browser window.  

It would be cool if this could be set as the default video mode, so we don't have to select it every time we watch a video. To make it perfect I would like it, if in this mode the header bar would be hidden as well (maybe a separate feature request?) to really maximize the available screen space for the video. 

For reference, the script [ResizeYoutubePlayerToWindowSize](https://github.com/Zren/ResizeYoutubePlayerToWindowSize) does for Youtube exactly what I would like to have for Nebula. 

Thanks for considering this request and this fantastic browser extension!

**Comment by BubiBalboa** [comment]
Wow, that was quick! It works as expected. Thank you!

To make it perfect it would be nice if scrolling down was still possible and the player remembered the setting.  But that's a bonus. If you keep the feature like it is right now I'm already happy. Thanks again.

**Comment by cpiber** [comment]
Allowing you to still scroll isn't as easy due to how the page is set up, currently I simply project it to the top. Maybe I'll look into it again in the future, but for now I'd like to leave it as-is.

As for remembering, it should keep the setting if you just navigate away (e.g. via the queue), but not if you reload. This is by design, there's the option to enable it by default, but I think remembering would get annoying really quickly, especially if you have multiple tabs open.

**Comment by BubiBalboa** [comment]
No worries then if it takes too much work for now. 

Not sure why multiple tabs would make it annoying? The way I use the site is I go to the video list, open a few interesting vids in new tabs and then watch them one after another. For that it would be nice if the setting could be remembered. I think having it as an optional thing in the settings menu doesn't hurt anyone. 

If you don't want this, that's fine, I'm already happy just to have the button on the player.
