### ISSUE TITLE
Feature Request: auto PiP

### ISSUE THREAD

**Issue by ewonais** [cpiber/NebulaEnhance#49]
Option to automaticly open PiP when switching tabs. Obly auto open  PiP if the video is playing.

**Comment by cpiber** [comment]
While there technically is a [PiP Api](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/requestPictureInPicture), I have not found a way to make this work...

Also, detecting switching of tabs requires special permissions for the extension, which I do not want add, and it is really easy to mess up. Also why would you even want that, the point of PiP is so that you can switch to a different tab?

I don't plan to add this
